"""Builds the human-readable learning report from a finished session."""

import logging
from pathlib import Path
from typing import Any, Dict, List

from chaos_sensei.core.session import Session

logger = logging.getLogger(__name__)


class ReportBuilder:
    """Converts session data into markdown/JSON incident reports."""

    def build_markdown(self, session: Session) -> str:
        """Render the full incident report as markdown."""
        scenario = session.scenario

        return f"""# Chaos Sensei Incident Report

## Session Information

- **Session ID**: {session.metadata.session_id}
- **Environment**: {session.metadata.environment}
- **Provider**: {session.metadata.provider}
- **Status**: {session.status.value if hasattr(session.status, "value") else session.status}
- **Created At**: {session.metadata.created_at}
- **Ended At**: {session.metadata.ended_at or "N/A"}

## Scenario

**Title**: {scenario.get("title", "Unknown")}

**Difficulty**: {scenario.get("difficulty", "Unknown")}

**Category**: {scenario.get("category", "Unknown")}

## Problem Description

{scenario.get("description", "No description available")}

## Visible Symptoms

{self._format_list(scenario.get("visible_symptoms", []))}

## Root Cause

{scenario.get("root_cause", "Root cause not available")}

## Ideal Debugging Path

{self._format_list(scenario.get("ideal_path", []))}

## Your Attempts

You requested {session.hint_count} hint(s).

Verification checks performed: {len(session.checks)}

Rolled back: {"yes" if session.rolled_back else "no"}

## Key Learnings

{self._format_list(scenario.get("learning_objectives", [
    "Always check service selector labels match pod labels",
    "Use `kubectl get endpoints` to verify service connectivity",
    "Events and logs provide crucial debugging context",
]))}

## Next Steps

1. Review the solution and understand the root cause
2. Practice similar scenarios to build muscle memory
3. Check the documentation for related concepts

---
Generated by Chaos Sensei
"""

    def build_json(self, session: Session) -> Dict[str, Any]:
        """Render the report as a structured dict."""
        return {
            "session": session.dict(),
        }

    def save(self, content: str, path: Path) -> None:
        """Write report content to disk, creating parent directories."""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        logger.info(f"Report saved to {path}")

    @staticmethod
    def _format_list(items: List[str]) -> str:
        """Format a list of strings as a markdown bullet list."""
        if not items:
            return "- None"
        return "\n".join(f"- {item}" for item in items)
